version: 2
updates:
  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directories:
      - /modules/ethereum
    schedule:
      interval: weekly
